Add --update-communities option
Signed-off-by: p4u <p4u@dabax.net>

diff --git a/cooker b/cooker
--- a/cooker
+++ b/cooker
@@ -13,7 +13,7 @@ J=${J:-$make_j}
 
 usage() {
     echo "Usage: $0 [-f [--force]] [-d <target> [--sdk|ib|force]] [-i <target> [--sdk-file=<file>|ib-file=<file>]] 
-                [--download-all|build-all|update-feeds] [--targets|flavors|communities|profiles=<target>] 
+                [--download-all|build-all|update-feeds] [--targets|flavors|communities|update-communities|profiles=<target>] 
                 [-b <target> [-j<N>] [--no-update|no-link-ib|remote|clean|force-local|package=<pkg>]]
                 [-c <target> [--profile=<profile>|no-update|remote|flavor=<flavor>|community=<path>|extra-pkg=<list>]] 
                 [--help]"
@@ -26,6 +26,7 @@ usage() {
     echo "    --profiles=<target>        : list available hardware profiles for a specific target"
     echo "    --flavors                  : list available LibreMesh flavors for cooking"
     echo "    --communities              : list available community profiles"
+    echo "    --update-communities       : update or download community profiles"
     echo "    --update-feeds             : update previously downloaded feeds (only works for Git feeds)"
     echo "    -f                         : download feeds based on feeds.conf.default file. Feeds will be shared among all targets"
     echo "       --force                 : force reinstall of feeds (remove old if exist)"
@@ -281,6 +282,11 @@ download_communities() {
             echo "-> Cannot fetch communities repository"
             exit 1
         }
+    } || {
+        cd $communities_dir && git pull || {
+            echo "-> Cannot update communities repository"
+            exit 1
+        }
     }
 }
 
@@ -404,7 +410,7 @@ list_profiles() {
 [ -z "$1" ] && usage
 OPTS=$(getopt -o hd:fb:c:d:i:j: -l targets,build-all,download-all,profiles:,flavors,profile:,flavor:,\
 update-feeds,no-update,no-link-ib,only-sdk,only-ib,remote,ib,sdk,sdk-file:,ib-file:,help,force,clean,\
-communities,community:,cook-all,package:,extra-pkg:,force-local -n $0 -- "$@")
+communities,update-communities,community:,cook-all,package:,extra-pkg:,force-local -n $0 -- "$@")
 eval set -- "$OPTS"
 
 while true; do
@@ -498,12 +504,12 @@ while true; do
             shift;shift
         ;;
         --clean)
-           sdk_clean=1
-           shift
+            sdk_clean=1
+            shift
         ;;
         --package)
-          package=$2
-          shift;shift
+            package=$2
+            shift;shift
         ;;
         -c)
             cook=1
@@ -524,6 +530,10 @@ while true; do
         ;;
         --force-local)
             force_local="1"
+            shift
+        ;;
+        --update-communities)
+            update_communities="1"
             shift
         ;;
         --community)
@@ -569,6 +579,8 @@ profile=${profile:-Default}
 [ "$download_feeds" == "1" ] && {
     download_feeds
 }
+
+[ "$update_communities" == "1" ] && download_communities
 
 [ "$build_sdk" == "1" ] && build_sdk $target
 
