Make download feeds mandatory and automatic (to simplify). Improve help.
Signed-off-by: Pau Escrich <p4u@dabax.net>

diff --git a/cooker b/cooker
--- a/cooker
+++ b/cooker
@@ -8,7 +8,7 @@
 J=${J:-$make_j}
 
 usage() {
-    echo "Usage: $0 [-f <feeds.conf.default>] [-d <target>] [-b <target> [--no-update]] [--download-all|build-all]"
+    echo "Usage: $0 [-f ] [-d <target>] [-b <target> [--no-update]] [--download-all|build-all|update-feeds]"
     echo "          [--targets|flavors|profiles=<target>] [-c <target> [--profile=<profile>] [--flavor=<flavor>]]"
     echo ""
     echo "    --download-all            : download all SDK and ImageBuilders"
@@ -19,19 +19,23 @@ usage() {
     echo "    --profile=<profile>       : use <profile> when cooking firmware (default is all available target profiles)"
     echo "    --flavors                 : list available LibreMesh flavors for cooking"
     echo "    --flavor=<flavor>         : use <flavor> when cooking firmware (default generic)"
-    echo "    --update-feeds            : update previously downloaded feeds (only works with Git feeds)"
+    echo "    --update-feeds            : update previously downloaded feeds (only works for Git feeds)"
     echo "    --no-update               : do not update feeds when building SDK"
-    echo "    -f <feeds.conf>           : download feeds based on feeds.conf file. Feeds will be shared among all targets"
+    echo "    -f                        : download feeds based on feeds.conf.default file. Feeds will be shared among all targets"
     echo "    -b <target>               : build specific target SDK"
     echo "    -d <target>               : download SDK and IB for specific target"
     echo "    -c <target>               : cook the firmware for specific target. Can be used with --profile and --flavor"
     echo ""
-    echo "Example of usage for building ar71xx target:"
+    echo "Example of usage for building SDK and cooking firmware for target tl-wdr3500-v1 (all in one)"
+    echo ""
+    echo "    $0 -c ar71xx/generic --flavor=generic --profile=tl-wdr3500-v1"
+    echo ""
+    echo "Example of usage for building SDK and cooking ar71xx target with all available profiles (step by step)"
     echo ""
     echo "    $0 -d ar71xx/generic"
-    echo "    $0 -f feeds.conf.default"
+    echo "    $0 -f"
     echo "    $0 -b ar71xx/generic"
-    echo "    $0 -c ar71xx/generic --profile=tl-wdr3500-v1 --flavor=generic"
+    echo "    $0 -c ar71xx/generic --flavor=generic"
     echo ""
 }
 
@@ -72,12 +76,9 @@ build_packets() {
     
     echo "-> Building $sdk"
     
-    [ -f $feeds_file ] && cp $feeds_file $sdk/feeds.conf || {
-        echo "-> Local feeds file not found, using standard remote feeds"
-        cp -f $sdk/feeds.conf.default $sdk/feeds.conf
-        echo "src-git libremesh $lime_repo;$lime_branch" >> $sdk/feeds.conf
-        echo "src-git libremap $limap_repo;$limap_branch" >> $sdk/feeds.conf
-        echo "src-git limeui $limeui_repo;$limeui_branch" >> $sdk/feeds.conf
+    [ -f "$feeds_file" ] || { 
+        echo "-> Local feeds file not found"
+        download_feeds
     }
     [ -z "$no_update" ] && (cd $sdk && scripts/feeds update -a)
     (cd $sdk && scripts/feeds install -p libremesh -a)
@@ -104,7 +105,7 @@ build_packets() {
 }
 
 download_feeds() {
-    local feeds_template="$1"
+    local feeds_template="$feeds_default_file"
     local output="$feeds_dir"
     rm -f $feeds_file
     [ ! -d "$output" ] && mkdir -p "$output"
@@ -242,7 +243,7 @@ while true; do
             break
         ;;
         -f)
-            download_feeds $2
+            download_feeds
             break
         ;;
         -b)
